/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.ProblemManagement.ejb;

/**
 * Local interface for ProblemManagement.
 * @generated 
 * @lomboz generated
 */
public interface ProblemManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
