/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.ProblemManagement.ejb;

/**
 * Remote interface for ProblemManagement.
 * @generated 
 * @lomboz generated
 */
public interface ProblemManagement
   extends javax.ejb.EJBObject
{

   public it.cnr.helpdesk.util.PageByPageIterator getUserProblemQueue( it.cnr.helpdesk.util.PageByPageIterator pagebypageiterator,it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemValueObject problemvalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.util.PageByPageIterator getExpertProblemQueue( it.cnr.helpdesk.util.PageByPageIterator pagebypageiterator,it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemValueObject problemvalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.Collection getProblemCountPerCategory( it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemCountValueObject problemcountvalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemValueObject getProblemDetail( long l, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.Collection getProblemEvents( long l, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject getProblemEventDetail( long l,java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.Collection getAllExpertProblems( java.lang.String esperto, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public void changeState( it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo,it.cnr.helpdesk.StateMachineManagement.javabeans.Transition transition )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.ArrayList sendNote( it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.ArrayList newProblem( it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemValueObject pvo, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.ArrayList newProblemFromExpert( it.cnr.helpdesk.ProblemManagement.valueobjects.ProblemValueObject pvo, java.lang.String instance )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.ArrayList modifyCategory( it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

   public java.util.ArrayList changeProblemExpert( it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo )
      throws it.cnr.helpdesk.ProblemManagement.exceptions.ProblemEJBException, java.rmi.RemoteException;

}
