/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.ProblemManagement.ejb;

/**
 * Session layer for ProblemManagement.
 * @generated 
 * @lomboz generated
 */
public class ProblemManagementSession
   extends it.cnr.helpdesk.ProblemManagement.ejb.ProblemManagementBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
