/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.ProblemManagement.ejb;

/**
 * Local home interface for ProblemManagement.
 * @generated 
 * @lomboz generated
 */
public interface ProblemManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ProblemManagementLocal";
   public static final String JNDI_NAME="ProblemManagementLocal";

   public it.cnr.helpdesk.ProblemManagement.ejb.ProblemManagementLocal create()
      throws javax.ejb.CreateException;

}
