/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.FaqManagement.ejb;

/**
 * Local interface for FaqManagement.
 * @generated 
 * @lomboz generated
 */
public interface FaqManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
