/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.FaqManagement.ejb;

/**
 * Local home interface for FaqManagement.
 * @generated 
 * @lomboz generated
 */
public interface FaqManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FaqManagementLocal";
   public static final String JNDI_NAME="FaqManagementLocal";

   public it.cnr.helpdesk.FaqManagement.ejb.FaqManagementLocal create()
      throws javax.ejb.CreateException;

}
