/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.FaqManagement.ejb;

/**
 * Home interface for FaqManagement.
 * @generated 
 * @lomboz generated
 */
public interface FaqManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FaqManagement";
   public static final String JNDI_NAME="comp/env/ejb/FaqManagement";

   public it.cnr.helpdesk.FaqManagement.ejb.FaqManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
