/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UserManagement.ejb;

/**
 * Home interface for UserManagement.
 * @generated 
 * @lomboz generated
 */
public interface UserManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserManagement";
   public static final String JNDI_NAME="comp/env/ejb/UserManagement";

   public it.cnr.helpdesk.UserManagement.ejb.UserManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
