/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UserManagement.ejb;

/**
 * Remote interface for UserManagement.
 * @generated 
 * @lomboz generated
 */
public interface UserManagement
   extends javax.ejb.EJBObject
{

   public void insertUser( it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject uservalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.util.PageByPageIterator allUsers( it.cnr.helpdesk.util.PageByPageIterator pagebypageiterator,it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject uservalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject isRegistered( it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject uservalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject getUserDetail( java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void updateUser( it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject uservalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void changeUserPassword( it.cnr.helpdesk.UserManagement.valueobjects.UserValueObject uservalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public java.lang.String getUserPassword( java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void deleteUser( java.lang.String login, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void disable( java.lang.String login,int profile,java.lang.String admin, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void enable( java.lang.String login, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public boolean existsAccount( java.lang.String login, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

   public void disable( java.lang.String login,int profile,java.lang.String admin,java.util.Collection eventi, java.lang.String instance )
      throws it.cnr.helpdesk.UserManagement.exceptions.UserEJBException, java.rmi.RemoteException;

}
