/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UserManagement.ejb;

/**
 * Local interface for UserManagement.
 * @generated 
 * @lomboz generated
 */
public interface UserManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
