/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UserManagement.ejb;

/**
 * Local home interface for UserManagement.
 * @generated 
 * @lomboz generated
 */
public interface UserManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserManagementLocal";
   public static final String JNDI_NAME="UserManagementLocal";

   public it.cnr.helpdesk.UserManagement.ejb.UserManagementLocal create()
      throws javax.ejb.CreateException;

}
