/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.StatisticsManagement.ejb;

/**
 * Local interface for StatisticsManagement.
 * @generated 
 * @lomboz generated
 */
public interface StatisticsManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
