/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.StatisticsManagement.ejb;

/**
 * Home interface for StatisticsManagement.
 * @generated 
 * @lomboz generated
 */
public interface StatisticsManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StatisticsManagement";
   public static final String JNDI_NAME="comp/env/ejb/StatisticsManagement";

   public it.cnr.helpdesk.StatisticsManagement.ejb.StatisticsManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
