/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.StatisticsManagement.ejb;

/**
 * Local home interface for StatisticsManagement.
 * @generated 
 * @lomboz generated
 */
public interface StatisticsManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StatisticsManagementLocal";
   public static final String JNDI_NAME="StatisticsManagementLocal";

   public it.cnr.helpdesk.StatisticsManagement.ejb.StatisticsManagementLocal create()
      throws javax.ejb.CreateException;

}
