/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.CategoryManagement.ejb;

/**
 * Remote interface for CategoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface CategoryManagement
   extends javax.ejb.EJBObject
{

   public it.cnr.helpdesk.CategoryManagement.valueobjects.CategoryValueObject allCategories( java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public java.util.Collection allCategoriesList( java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public java.util.Collection allExpertCategoriesList( java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public void assignCategoryToExpert( int i,java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public void removeCategoryFromExpert( int i,java.lang.String s, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public int insertCategory( it.cnr.helpdesk.CategoryManagement.valueobjects.CategoryValueObject categoryvalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public void disable( int id, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public void enable( int id, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

   public void updateCategory( it.cnr.helpdesk.CategoryManagement.valueobjects.CategoryValueObject categoryvalueobject, java.lang.String instance )
      throws it.cnr.helpdesk.CategoryManagement.exceptions.CategoryEJBException, java.rmi.RemoteException;

}
