/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.CategoryManagement.ejb;

/**
 * Local home interface for CategoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface CategoryManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CategoryManagementLocal";
   public static final String JNDI_NAME="CategoryManagementLocal";

   public it.cnr.helpdesk.CategoryManagement.ejb.CategoryManagementLocal create()
      throws javax.ejb.CreateException;

}
