/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.CategoryManagement.ejb;

/**
 * Home interface for CategoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface CategoryManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CategoryManagement";
   public static final String JNDI_NAME="comp/env/ejb/CategoryManagement";

   public it.cnr.helpdesk.CategoryManagement.ejb.CategoryManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
