/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.CategoryManagement.ejb;

/**
 * Local interface for CategoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface CategoryManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
