/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.AttachmentManagement.ejb;

/**
 * Home interface for AttachmentEJB.
 * @generated 
 * @lomboz generated
 */
public interface AttachmentEJBHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AttachmentEJB";
   public static final String JNDI_NAME="AttachmentEJB";

   public it.cnr.helpdesk.AttachmentManagement.ejb.AttachmentEJB create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
