/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.AttachmentManagement.ejb;

/**
 * Session layer for AttachmentEJB.
 * @generated 
 * @lomboz generated
 */
public class AttachmentEJBSession
   extends it.cnr.helpdesk.AttachmentManagement.ejb.AttachmentBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
