/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.AttachmentManagement.ejb;


/**
 * Remote interface for AttachmentEJB.
 * @generated 
 * @lomboz generated
 */
public interface AttachmentEJB
   extends javax.ejb.EJBObject
{

   public java.util.ArrayList insert( it.cnr.helpdesk.AttachmentManagement.valueobjects.AttachmentValueObject avo, it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo, java.lang.String instance )
      throws it.cnr.helpdesk.AttachmentManagement.exceptions.AttachmentEJBException, java.rmi.RemoteException;

   public void update( it.cnr.helpdesk.AttachmentManagement.valueobjects.AttachmentValueObject avo, java.lang.String instance )
      throws it.cnr.helpdesk.AttachmentManagement.exceptions.AttachmentEJBException, java.rmi.RemoteException;

   public void preInsert( it.cnr.helpdesk.AttachmentManagement.valueobjects.AttachmentValueObject avo, java.lang.String instance )
      throws it.cnr.helpdesk.AttachmentManagement.exceptions.AttachmentEJBException, java.rmi.RemoteException;

   public java.util.ArrayList confirmPreinsert( it.cnr.helpdesk.AttachmentManagement.valueobjects.AttachmentValueObject avo, it.cnr.helpdesk.ProblemManagement.valueobjects.EventValueObject evo, java.lang.String instance )
      throws it.cnr.helpdesk.AttachmentManagement.exceptions.AttachmentEJBException, java.rmi.RemoteException;
   
   public void delete( it.cnr.helpdesk.AttachmentManagement.valueobjects.AttachmentValueObject avo, java.lang.String instance) 
      throws it.cnr.helpdesk.AttachmentManagement.exceptions.AttachmentEJBException,  java.rmi.RemoteException;
}
