/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.AttachmentManagement.ejb;

/**
 * Local home interface for AttachmentEJB.
 * @generated 
 * @lomboz generated
 */
public interface AttachmentEJBLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AttachmentEJBLocal";
   public static final String JNDI_NAME="AttachmentEJBLocal";

   public it.cnr.helpdesk.AttachmentManagement.ejb.AttachmentEJBLocal create()
      throws javax.ejb.CreateException;

}
