/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.AttachmentManagement.ejb;

/**
 * Local interface for AttachmentEJB.
 * @generated 
 * @lomboz generated
 */
public interface AttachmentEJBLocal
   extends javax.ejb.EJBLocalObject
{

}
