/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MailParserManagement.ejb;

/**
 * Local home interface for MailParserManagement.
 * @generated 
 * @lomboz generated
 */
public interface MailParserManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MailParserManagementLocal";
   public static final String JNDI_NAME="MailParserManagementLocal";

   public it.cnr.helpdesk.MailParserManagement.ejb.MailParserManagementLocal create()
      throws javax.ejb.CreateException;

}
