/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MailParserManagement.ejb;

/**
 * Home interface for MailParserManagement.
 * @generated 
 * @lomboz generated
 */
public interface MailParserManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MailParserManagement";
   public static final String JNDI_NAME="comp/env/ejb/MailParserManagement";

   public it.cnr.helpdesk.MailParserManagement.ejb.MailParserManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
