/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MailParserManagement.ejb;

/**
 * Local interface for MailParserManagement.
 * @generated 
 * @lomboz generated
 */
public interface MailParserManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
