/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MailParserManagement.ejb;

/**
 * Session layer for MailParserManagement.
 * @generated 
 * @lomboz generated
 */
public class MailParserManagementSession
   extends it.cnr.helpdesk.MailParserManagement.ejb.MailBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
