/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.EventManagement.ejb;

/**
 * Local interface for EventManagement.
 * @generated 
 * @lomboz generated
 */
public interface EventManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
