/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.EventManagement.ejb;

/**
 * Local home interface for EventManagement.
 * @generated 
 * @lomboz generated
 */
public interface EventManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EventManagementLocal";
   public static final String JNDI_NAME="EventManagementLocal";

   public it.cnr.helpdesk.EventManagement.ejb.EventManagementLocal create()
      throws javax.ejb.CreateException;

}
