/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.EventManagement.ejb;

/**
 * Remote interface for EventManagement.
 * @generated 
 * @lomboz generated
 */
public interface EventManagement
   extends javax.ejb.EJBObject
{

   public java.util.Collection getProblemEvents( long l,boolean filter, java.lang.String instance )
      throws it.cnr.helpdesk.EventManagement.exceptions.EventEJBException, java.rmi.RemoteException;

}
