/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.EventManagement.ejb;

/**
 * Home interface for EventManagement.
 * @generated 
 * @lomboz generated
 */
public interface EventManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EventManagement";
   public static final String JNDI_NAME="comp/env/ejb/EventManagement";

   public it.cnr.helpdesk.EventManagement.ejb.EventManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
