/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.EventManagement.ejb;

/**
 * Session layer for EventManagement.
 * @generated 
 * @lomboz generated
 */
public class EventManagementSession
   extends it.cnr.helpdesk.EventManagement.ejb.EventManagementBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
