/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.RepositoryManagement.ejb;

/**
 * Home interface for RepositoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface RepositoryManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RepositoryManagement";
   public static final String JNDI_NAME="comp/env/ejb/RepositoryManagement";

   public it.cnr.helpdesk.RepositoryManagement.ejb.RepositoryManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
