/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.RepositoryManagement.ejb;

/**
 * Local interface for RepositoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface RepositoryManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
