/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.RepositoryManagement.ejb;

/**
 * Local home interface for RepositoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface RepositoryManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RepositoryManagementLocal";
   public static final String JNDI_NAME="RepositoryManagementLocal";

   public it.cnr.helpdesk.RepositoryManagement.ejb.RepositoryManagementLocal create()
      throws javax.ejb.CreateException;

}
