/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.RepositoryManagement.ejb;

/**
 * Remote interface for RepositoryManagement.
 * @generated 
 * @lomboz generated
 */
public interface RepositoryManagement
   extends javax.ejb.EJBObject
{

   public void addRow( it.cnr.helpdesk.RepositoryManagement.valueobjects.RepositoryValueObject rvo, java.lang.String instance )
      throws it.cnr.helpdesk.RepositoryManagement.exceptions.RepositoryEJBException, java.rmi.RemoteException;

   public java.lang.String createReport( java.lang.String categoria,java.lang.String inizio,java.lang.String fine, java.lang.String instance )
      throws it.cnr.helpdesk.RepositoryManagement.exceptions.RepositoryEJBException, java.rmi.RemoteException;

   public void updateAttachment( it.cnr.helpdesk.RepositoryManagement.valueobjects.RepositoryValueObject rvo, java.lang.String instance )
      throws it.cnr.helpdesk.RepositoryManagement.exceptions.RepositoryEJBException, java.rmi.RemoteException;

   public void deleteRow( it.cnr.helpdesk.RepositoryManagement.valueobjects.RepositoryValueObject rvo, java.lang.String instance )
      throws it.cnr.helpdesk.RepositoryManagement.exceptions.RepositoryEJBException, java.rmi.RemoteException;

}
