/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UOManagement.ejb;

/**
 * Remote interface for UOManagement.
 * @generated 
 * @lomboz generated
 */
public interface UOManagement
   extends javax.ejb.EJBObject
{

   public java.lang.String executeInsert( it.cnr.helpdesk.UOManagement.valueobjects.UOValueObject uov, java.lang.String instance )
      throws java.rmi.RemoteException;

   public void executeUpdate( it.cnr.helpdesk.UOManagement.valueobjects.UOValueObject uov, java.lang.String instance )
      throws java.rmi.RemoteException;

   public void executeDelete( it.cnr.helpdesk.UOManagement.valueobjects.UOValueObject uov, java.lang.String instance )
      throws java.rmi.RemoteException;

   public java.util.Collection getStructures( java.lang.String instance )
      throws java.rmi.RemoteException;

   public java.util.Collection getAllStructures( java.lang.String instance )
      throws java.rmi.RemoteException;

   public it.cnr.helpdesk.UOManagement.valueobjects.UOValueObject getOneStructure( java.lang.String cod, java.lang.String instance )
      throws java.rmi.RemoteException;

   public void enabled( java.lang.String cod, java.lang.String instance )
      throws java.rmi.RemoteException;

   public void disabled( java.lang.String cod, java.lang.String instance )
      throws java.rmi.RemoteException;

}
