/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UOManagement.ejb;

/**
 * Local interface for UOManagement.
 * @generated 
 * @lomboz generated
 */
public interface UOManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
