/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UOManagement.ejb;

/**
 * Local home interface for UOManagement.
 * @generated 
 * @lomboz generated
 */
public interface UOManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UOManagementLocal";
   public static final String JNDI_NAME="UOManagementLocal";

   public it.cnr.helpdesk.UOManagement.ejb.UOManagementLocal create()
      throws javax.ejb.CreateException;

}
