/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UOManagement.ejb;

/**
 * Session layer for UOManagement.
 * @generated 
 * @lomboz generated
 */
public class UOManagementSession
   extends it.cnr.helpdesk.UOManagement.ejb.UOManagementBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
