/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.UOManagement.ejb;

/**
 * Home interface for UOManagement.
 * @generated 
 * @lomboz generated
 */
public interface UOManagementHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UOManagement";
   public static final String JNDI_NAME="comp/env/ejb/UOManagement";

   public it.cnr.helpdesk.UOManagement.ejb.UOManagement create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
