/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.StateMachineManagement.ejb;

/**
 * Local interface for StateMachineManagement.
 * @generated 
 * @lomboz generated
 */
public interface StateMachineManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
