/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.StateMachineManagement.ejb;

/**
 * Local home interface for StateMachineManagement.
 * @generated 
 * @lomboz generated
 */
public interface StateMachineManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/StateMachineManagementLocal";
   public static final String JNDI_NAME="StateMachineManagementLocal";

   public it.cnr.helpdesk.StateMachineManagement.ejb.StateMachineManagementLocal create()
      throws javax.ejb.CreateException;

}
