/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MessageManagement.ejb;

/**
 * Local interface for MessageManagement.
 * @generated 
 * @lomboz generated
 */
public interface MessageManagementLocal
   extends javax.ejb.EJBLocalObject
{

}
