/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MessageManagement.ejb;

/**
 * Remote interface for MessageManagement.
 * @generated 
 * @lomboz generated
 */
public interface MessageManagement
   extends javax.ejb.EJBObject
{

   public int executeInsert( it.cnr.helpdesk.MessageManagement.valueobjects.MessageValueObject mvo, java.lang.String instance )
      throws it.cnr.helpdesk.MessageManagement.exceptions.MessageEJBException, java.rmi.RemoteException;

}
