/*
 * Generated by XDoclet - Do not edit!
 */
package it.cnr.helpdesk.MessageManagement.ejb;

/**
 * Local home interface for MessageManagement.
 * @generated 
 * @lomboz generated
 */
public interface MessageManagementLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MessageManagementLocal";
   public static final String JNDI_NAME="MessageManagementLocal";

   public it.cnr.helpdesk.MessageManagement.ejb.MessageManagementLocal create()
      throws javax.ejb.CreateException;

}
